Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
pd.set_option('precision', 8)

pd.DataFrame({
    'Numerical': [F(x), F(x, 1), F(x,2), F(x, -1)],
    'Analytic': [f(x), d1(x), d2(x), np.exp(1)-1]},
    index = ['Function', 'First Derivative', 'Second Derivative', 'Definite Integral']
)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mOptionError[0m                               Traceback (most recent call last)
Input [1;32mIn [8][0m, in [0;36m<cell line: 1>[1;34m()[0m
[1;32m----> 1[0m [43mpd[49m[38;5;241;43m.[39;49m[43mset_option[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43mprecision[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m [49m[38;5;241;43m8[39;49m[43m)[49m
[0;32m      3[0m pd[38;5;241m.[39mDataFrame({
[0;32m      4[0m     [38;5;124m'[39m[38;5;124mNumerical[39m[38;5;124m'[39m: [F(x), F(x, [38;5;241m1[39m), F(x,[38;5;241m2[39m), F(x, [38;5;241m-[39m[38;5;241m1[39m)],
[0;32m      5[0m     [38;5;124m'[39m[38;5;124mAnalytic[39m[38;5;124m'[39m: [f(x), d1(x), d2(x), np[38;5;241m.[39mexp([38;5;241m1[39m)[38;5;241m-[39m[38;5;241m1[39m]},
[0;32m      6[0m     index [38;5;241m=[39m [[38;5;124m'[39m[38;5;124mFunction[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mFirst Derivative[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mSecond Derivative[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mDefinite Integral[39m[38;5;124m'[39m]
[0;32m      7[0m )

File [1;32mC:\ProgramData\Anaconda3\lib\site-packages\pandas\_config\config.py:256[0m, in [0;36mCallableDynamicDoc.__call__[1;34m(self, *args, **kwds)[0m
[0;32m    255[0m [38;5;28;01mdef[39;00m [38;5;21m__call__[39m([38;5;28mself[39m, [38;5;241m*[39margs, [38;5;241m*[39m[38;5;241m*[39mkwds):
[1;32m--> 256[0m     [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39m[38;5;18m__func__[39m([38;5;241m*[39margs, [38;5;241m*[39m[38;5;241m*[39mkwds)

File [1;32mC:\ProgramData\Anaconda3\lib\site-packages\pandas\_config\config.py:149[0m, in [0;36m_set_option[1;34m(*args, **kwargs)[0m
[0;32m    146[0m     [38;5;28;01mraise[39;00m [38;5;167;01mTypeError[39;00m([38;5;124mf[39m[38;5;124m'[39m[38;5;124m_set_option() got an unexpected keyword argument [39m[38;5;124m"[39m[38;5;132;01m{[39;00mkwarg[38;5;132;01m}[39;00m[38;5;124m"[39m[38;5;124m'[39m)
[0;32m    148[0m [38;5;28;01mfor[39;00m k, v [38;5;129;01min[39;00m [38;5;28mzip[39m(args[::[38;5;241m2[39m], args[[38;5;241m1[39m::[38;5;241m2[39m]):
[1;32m--> 149[0m     key [38;5;241m=[39m [43m_get_single_key[49m[43m([49m[43mk[49m[43m,[49m[43m [49m[43msilent[49m[43m)[49m
[0;32m    151[0m     o [38;5;241m=[39m _get_registered_option(key)
[0;32m    152[0m     [38;5;28;01mif[39;00m o [38;5;129;01mand[39;00m o[38;5;241m.[39mvalidator:

File [1;32mC:\ProgramData\Anaconda3\lib\site-packages\pandas\_config\config.py:116[0m, in [0;36m_get_single_key[1;34m(pat, silent)[0m
[0;32m    114[0m     [38;5;28;01mraise[39;00m OptionError([38;5;124mf[39m[38;5;124m"[39m[38;5;124mNo such keys(s): [39m[38;5;132;01m{[39;00m[38;5;28mrepr[39m(pat)[38;5;132;01m}[39;00m[38;5;124m"[39m)
[0;32m    115[0m [38;5;28;01mif[39;00m [38;5;28mlen[39m(keys) [38;5;241m>[39m [38;5;241m1[39m:
[1;32m--> 116[0m     [38;5;28;01mraise[39;00m OptionError([38;5;124m"[39m[38;5;124mPattern matched multiple keys[39m[38;5;124m"[39m)
[0;32m    117[0m key [38;5;241m=[39m keys[[38;5;241m0[39m]
[0;32m    119[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m silent:

[1;31mOptionError[0m: 'Pattern matched multiple keys'
OptionError: 'Pattern matched multiple keys'

