Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\randa\AppData\Roaming\Python\Python39\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\randa\AppData\Roaming\Python\Python39\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\randa\AppData\Roaming\Python\Python39\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\randa\AppData\Roaming\Python\Python39\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\randa\AppData\Roaming\Python\Python39\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\randa\AppData\Roaming\Python\Python39\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Ploting Limits
x1lim = [-5, 4]
x2lim = [-6, 4]

# Compute Separatrix
T = 10;
problem2 = ODE(f,T,B,a,b)
problem2.spx()

x = np.array([problem.x.values.T for problem in problems])

# Compute Nullclines
x1 = np.linspace(*x1lim, 100)
xnulls = pd.DataFrame({'$x_1$ Nullcline': (x1**2-a)/2,
                       '$x_2$ Nullcline': b-x1},
                     index = x1)

# Plot Phase Diagram
fig, ax =  plt.subplots()

for txt, xy in zip('AB', [A,B]):
    ax.annotate(txt, xy + [0.1,0.2])
    
for i, xy in enumerate(x[:,:,0]):
    ax.annotate(str(i), xy+[0,0.20], color='C2', ha='center', fontsize=14)

problem.phase(x1lim, x2lim, 
              xnulls=xnulls, 
              xstst=np.r_[A,B],
              x=x,
              title='ODE Phase Diagram',
              ax=ax,
              animated=5  # requires ffmpeg for video, change to 0 for static image
             )
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mRuntimeError[0m                              Traceback (most recent call last)
[1;32m~\AppData\Local\Temp\ipykernel_12136\4283567534.py[0m in [0;36m<cell line: 27>[1;34m()[0m
[0;32m     25[0m     [0max[0m[1;33m.[0m[0mannotate[0m[1;33m([0m[0mstr[0m[1;33m([0m[0mi[0m[1;33m)[0m[1;33m,[0m [0mxy[0m[1;33m+[0m[1;33m[[0m[1;36m0[0m[1;33m,[0m[1;36m0.20[0m[1;33m][0m[1;33m,[0m [0mcolor[0m[1;33m=[0m[1;34m'C2'[0m[1;33m,[0m [0mha[0m[1;33m=[0m[1;34m'center'[0m[1;33m,[0m [0mfontsize[0m[1;33m=[0m[1;36m14[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m     26[0m [1;33m[0m[0m
[1;32m---> 27[1;33m problem.phase(x1lim, x2lim, 
[0m[0;32m     28[0m               [0mxnulls[0m[1;33m=[0m[0mxnulls[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m
[0;32m     29[0m               [0mxstst[0m[1;33m=[0m[0mnp[0m[1;33m.[0m[0mr_[0m[1;33m[[0m[0mA[0m[1;33m,[0m[0mB[0m[1;33m][0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m

[1;32mC:\ProgramData\Anaconda3\lib\site-packages\compecon\ode.py[0m in [0;36mphase[1;34m(self, x1lim, x2lim, x, xstst, xnulls, ax, animated, xnulls_kw, xstst_kw, path_kw, **ax_kwargs)[0m
[0;32m    272[0m [1;33m[0m[0m
[0;32m    273[0m             [0mani[0m [1;33m=[0m [0mFuncAnimation[0m[1;33m([0m[0mfig[0m[1;33m,[0m [0manimate[0m[1;33m,[0m [0mframes[0m[1;33m=[0m[0mtotal_frames[0m[1;33m,[0m [0minterval[0m[1;33m=[0m[0minterval[0m[1;33m,[0m [0mrepeat[0m[1;33m=[0m[1;32mFalse[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 274[1;33m             [1;32mreturn[0m [0mHTML[0m[1;33m([0m[0mani[0m[1;33m.[0m[0mto_html5_video[0m[1;33m([0m[1;33m)[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    275[0m [1;33m[0m[0m
[0;32m    276[0m         [1;32melse[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;32mC:\ProgramData\Anaconda3\lib\site-packages\matplotlib\animation.py[0m in [0;36mto_html5_video[1;34m(self, embed_limit)[0m
[0;32m   1262[0m                 [1;31m# We create a writer manually so that we can get the[0m[1;33m[0m[1;33m[0m[0m
[0;32m   1263[0m                 [1;31m# appropriate size for the tag[0m[1;33m[0m[1;33m[0m[0m
[1;32m-> 1264[1;33m                 [0mWriter[0m [1;33m=[0m [0mwriters[0m[1;33m[[0m[0mmpl[0m[1;33m.[0m[0mrcParams[0m[1;33m[[0m[1;34m'animation.writer'[0m[1;33m][0m[1;33m][0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m   1265[0m                 writer = Writer(codec='h264',
[0;32m   1266[0m                                 [0mbitrate[0m[1;33m=[0m[0mmpl[0m[1;33m.[0m[0mrcParams[0m[1;33m[[0m[1;34m'animation.bitrate'[0m[1;33m][0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m

[1;32mC:\ProgramData\Anaconda3\lib\site-packages\matplotlib\animation.py[0m in [0;36m__getitem__[1;34m(self, name)[0m
[0;32m    149[0m         [1;32mif[0m [0mself[0m[1;33m.[0m[0mis_available[0m[1;33m([0m[0mname[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m    150[0m             [1;32mreturn[0m [0mself[0m[1;33m.[0m[0m_registered[0m[1;33m[[0m[0mname[0m[1;33m][0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 151[1;33m         [1;32mraise[0m [0mRuntimeError[0m[1;33m([0m[1;34mf"Requested MovieWriter ({name}) not available"[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    152[0m [1;33m[0m[0m
[0;32m    153[0m [1;33m[0m[0m

[1;31mRuntimeError[0m: Requested MovieWriter (ffmpeg) not available
RuntimeError: Requested MovieWriter (ffmpeg) not available

